export const Fonts = {
    OpenSans_regular: 'OpenSans',
    OpenSans_semibold: 'OpenSans-Semibold',
    OpenSans_Bold: 'OpenSans-Bold',
    PlayfairDisplay_Bold: 'PlayfairDisplay-Bold',
    PlayfairDisplay_Black:"PlayfairDisplay-Black",
    PlayfairDisplay_Regular:"PlayfairDisplay-Regular",
    OpenSans_Light:"OpenSans-Light",
    BennetTextOne_SemiBold_Italic:'BennetTextOne_SemiBold_Italic',
    BennetTextOne_SemiBold:'BennetTextOne_SemiBold',
    BennetTextOne:'BennetTextOne',
    BennetTextThree_Bold_Italic:'BennetTextThree_Bold_Italic',
    BennetTextThree_Bold:'BennetTextThree_Bold',
    BennetTextThree_Italic:'BennetTextThree_Italic',
    BennetTextThree_SemiBold_Italic:'BennetTextThree_SemiBold_Italic',
    BennetTextThree_SemiBold:'BennetTextThree_SemiBold',
    BennetTextThree:'BennetTextThree',
    BennetTextTwo_Bold_Italic:'BennetTextTwo_Bold_Italic',
    BennetTextTwo_Bold:'BennetTextTwo_Bold',
    BennetTextTwo_Italic:'BennetTextTwo_Italic',
    BennetTextTwo_SemiBold_Italic:'BennetTextTwo_SemiBold_Italic',
    BennetTextTwo_SemiBold:'BennetTextTwo_SemiBold',
    BennetTextTwo:'BennetTextTwo',
    BennetTextFour_Bold_Italic:'BennetTextFour_Bold_Italic',
    BennetTextFour_Bold:'BennetTextFour_Bold',
    BennetTextFour_Italic:'BennetTextFour_Italic',
    BennetTextFour_SemiBold_Italic:'BennetTextFour_SemiBold_Italic',
    BennetTextFour_SemiBold:'BennetTextFour_SemiBold',
    BennetTextFour:'BennetTextFour',
    BennetTextOne_Bold_Italic:'BennetTextOne_Bold_Italic',
    BennetTextOne_Bold:'BennetTextOne_Bold',
    BennetTextOne_Italic:'BennetTextOne_Italic',
    Righteous_Regular:'Righteous_Regular',
}