export const Images = {
  domino_logo: require('../assets/images/domino_logo.png'),
  domino_gif: require('../assets/images/domino_gif.gif'),
  woodenBackground: require('../assets/images/woodenBackground.jpg'),
  gameTypeBg: require('../assets/images/gameTypeBg.png'),
  playButton: require('../assets/images/playButton1.png'),
  dominoDice: require('../assets/images/dice.png'),
  next: require('../assets/images/next.png'),
  back: require('../assets/images/back.png'),
  nextArrow: require('../assets/images/nextArrow.png'),
  start: require('../assets/images/start.png'),
  findUserNameBackground: require('../assets/images/findUserNameBackground2.png'),
  winanim: require('../assets/images/winanim1.gif'),
  boardcenterlogo1: require('../assets/images/boardcenterlog1.png'),
  boardcenterlogo2: require('../assets/images/boardcenterlog2.png'),
  AppLogo: require('../assets/images/Applogo.jpeg'),
  reload1: require('../assets/images/reload.png'),
  user2: require('../assets/images/2_1user.png'),
  user3: require('../assets/images/3user.png'),
  user4: require('../assets/images/4user.png'),
};
